name: fedora 41

on:
  push:
    branches:
      - main
      - devel
  pull_request:


jobs:
  container-test-job:
    runs-on: ubuntu-latest
    container:
      image: fedora:41
    steps:
    - name: checkout
      uses: actions/checkout@v4
    - name: install packages
      run: yes | dnf install automake gcc which g++ nettle-devel
    - name: bootstrap
      run: ./bootstrap.sh
    - name: configure
      run: ./configure --enable-warnings CXXFLAGS=-std=c++17
    - name: make
      run: make -j $(nproc)
    - name: make check
      run: make check
    - name: make distcheck
      run: make distcheck CXXFLAGS=-std=c++17
    - name: store the logs as an artifact
      if: ${{ always() }}
      uses: actions/upload-artifact@v4
      with:
         path: '**/*.log'
