name: gcc 11

on: [push, pull_request]


jobs:
  build:
    name: Compiles with gcc 11
    runs-on: ubuntu-20.04

    steps:
    - name: checkout
      uses: actions/checkout@v2
    - name: install packages
      run: sudo apt install build-essential nettle-dev time gcc-11 g++-11
    - name: bootstrap
      run: ./bootstrap.sh
    - name: configure
      run: ./configure CXX=g++-11
    - name: build
      run: make
    - name: check
      run: make check
    - name: store the logs as an artifact
      if: ${{ always() }}
      uses: actions/upload-artifact@v2.2.4
      with:
         path: '**/*.log'

