name: gcc 13

on: [push, pull_request]


jobs:
  build:
    name: Compiles with gcc 13
    runs-on: ubuntu-22.04

    steps:
    - name: checkout
      uses: actions/checkout@v3
    - name: add ppa
      run: |
        sudo add-apt-repository ppa:ubuntu-toolchain-r/test
        sudo apt-get update
    - name: install packages
      run: sudo apt install build-essential nettle-dev time gcc-13 g++-13
    - name: bootstrap
      run: ./bootstrap.sh
    - name: configure
      run: ./configure CXX=g++-13
    - name: build
      run: make
    - name: check
      run: make check
    - name: store the logs as an artifact
      if: ${{ always() }}
      uses: actions/upload-artifact@v3
      with:
         path: '**/*.log'

