name: gcc 14

on:
  push:
    branches:
      - main
      - devel
  pull_request:

jobs:
  build:
    name: Compiles with gcc 14
    runs-on: ubuntu-24.04

    steps:
    - name: checkout
      uses: actions/checkout@v4
    - name: install packages
      run: sudo apt install build-essential nettle-dev time gcc-14 g++-14
    - name: bootstrap
      run: ./bootstrap.sh
    - name: configure
      run: ./configure CXX=g++-14 CXXFLAGS=-std=c++17
    - name: build
      run: make
    - name: check
      run: make check
    - name: store the logs as an artifact
      if: ${{ always() }}
      uses: actions/upload-artifact@v4
      with:
         path: '**/*.log'

