name: mac os x default build

on: [push]

jobs:
  build:
    name: Test on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest]

    steps:
    - name: checkout
      uses: actions/checkout@v2
    - name: install packages
      run: brew install libnettle automake autoconf
    - name: bootstrap
      run: ./bootstrap.sh
    - name: configure
      run: ./configure --enable-warnings CXXFLAGS=-std=c++11
    - name: make
      run: make
# tests fail because readlink does not understand -f on mac      
#    - name: make check
#      run: make check
#    - name: make distcheck
#      run: make distcheck CXXFLAGS=-std=c++11
    - name: Upload a Build Artifact
      if: ${{ always() }}
      uses: actions/upload-artifact@v2.2.4
      with:
         path: '**/*.log'
